### ISSUE TITLE
set Window size?

### ISSUE THREAD

**Issue by scotts777** [caerwynj/acme-sac#40]
Not sure if this is a duplicate of:
[https://github.com/caerwynj/acme-sac/issues/13](url)

But on Windows 10, I can't resize the window to fill out the entire Display
size.  Is there a setting parameter to define the size of the
Acme application window on startup?

**Comment by eekee** [comment]
Issue 13 is a bit of a mess, and I think most of the issues within it were fixed long ago.

I couldn't resize the window to fill the screen in Win7. It was particularly annoying because Acme needs width, more so with the large fonts I need, and Acme-Sac wouldn't go wider than about 2/3 the screen width.

**Comment by eekee** [comment]
For the purposes of reproduction, I should add I had Windows set to increase font size. I forget the name of the option in Win7. I used the classic Windows theme to stop it being applied to old programs.

When I tried Acme-SAC in Win10 which has no classic theme, it rendered in a very distorted way. MS has since changed how increased text size works for old programs, but I haven't re-tested.

**Comment by scotts777** [comment]
caerwyn gave me the answer I was looking for here:
[https://groups.google.com/d/msg/acme-sac/14V1naKRb0c/_j5Fy83dCAAJ](url)

> Start Acme.exe with arguments such as this:
Acme.exe -g1600x1024
The default is 1280x1024, which you can edit in /sys/emu/port/main.c:/Xzsize
See the man page for emu for more details of the command line arguments for Acme.exe.  It's basically just emu.exe renamed. 

>
